### ISSUE TITLE
installing/compiling the code

### ISSUE THREAD

**Issue by thaboub** [chenming-wu/pymdp#1]
Hello Wu
I am so glad to see you putting the code of pymdp in github, that is very helpful to get into your contribution in the field of 3D printing.

I tried to run the code locally, I went through all the requirements and I installed all the prerequisites, but when I got to to the last step and run the following 
python -m pip install pymdp

I am getting the following errors
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
Installing collected packages: pyyaml, torch, nose, pymdp
  Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mbely\\AppData\\Local\\Temp\\pip-install-0vdx9x0v\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\mbely\\AppData\\Local\\Temp\\pip-install-0vdx9x0v\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\mbely\AppData\Local\Temp\pip-record-s8_qq5wg\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\mbely\AppData\Local\Temp\pip-install-0vdx9x0v\torch\
...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Are you aware of the root cause of this issue? Can you please help if you have any workarounds or how I can fix it?

I really appreciate your help and thank you very much again for making your work accessible. 
It is really valuable!

**Comment by chenming-wu** [comment]
Now it supports VCPKG to facilate the compilation process, which will resolve the problem of inconsistent environments. Please feel free to reopen this issue if you still have any problem in compiling the library!
